USE [labelmanager_combine2]
GO

/****** Object:  Table [its_labelmanager].[BM_RICH_LABELSIZE_FORM]    Script Date: 2026-07-03 오후 3:22:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM](
	[RICH_LABELSIZE_ID] [int] IDENTITY(1,1) NOT NULL,
	[RICH_BRAND_ID] [int] NOT NULL,
	[RICH_LABELSIZE_NAME] [varchar](50) NOT NULL,
	[RICH_FORM_WIDTH] [smallint] NOT NULL,
	[RICH_FORM_HEIGHT] [smallint] NOT NULL,
	[RICH_FORM_DATA] [varchar](max) NOT NULL,
	[RICH_SETUP_LEFT] [smallint] NOT NULL,
	[RICH_SETUP_TOP] [smallint] NOT NULL,
	[RICH_SETUP_READONLY] [tinyint] NOT NULL,
	[RICH_SETUP_MAKEDATE_TYPE] [tinyint] NOT NULL,
	[RICH_SETUP_MAKETIME_TYPE] [tinyint] NOT NULL,
	[RICH_SETUP_VALIDDATE_TYPE] [tinyint] NOT NULL,
	[RICH_SETUP_VALIDTIME_TYPE] [tinyint] NOT NULL,
	[RICH_SETUP_USE_MAKEDATE] [tinyint] NOT NULL,
	[RICH_SETUP_USE_MAKETIME] [tinyint] NOT NULL,
	[RICH_SETUP_USE_VALIDDATE] [tinyint] NOT NULL,
	[RICH_SETUP_USE_VALIDTIME] [tinyint] NOT NULL,
	[RICH_SETUP_LINEFEED] [smallint] NOT NULL,
	[RICH_SETUP_USE_SCALE] [tinyint] NOT NULL,
	[RICH_SETUP_USE_SHORT_YEAR] [tinyint] NOT NULL,
	[RICH_LABELSIZE_ORDER] [int] NOT NULL,
	[RICH_USER_MAKEDATE] [varchar](50) NULL,
	[RICH_USER_MAKETIME] [varchar](50) NULL,
	[RICH_USER_VALIDDATE] [varchar](50) NULL,
	[RICH_USER_VALIDTIME] [varchar](50) NULL,
	[RICH_USE_MULTI_LINE] [tinyint] NULL,
	[RICH_SPACE_MULTI_LINE] [int] NULL,
	[RICH_LOCK_EDIT] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RICH_LABELSIZE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_FORM_WIDTH]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_FORM_HEIGHT]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ('') FOR [RICH_FORM_DATA]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_LEFT]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_TOP]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_READONLY]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_MAKEDATE_TYPE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_MAKETIME_TYPE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_VALIDDATE_TYPE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_SETUP_VALIDTIME_TYPE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((1)) FOR [RICH_SETUP_USE_MAKEDATE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((1)) FOR [RICH_SETUP_USE_MAKETIME]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((1)) FOR [RICH_SETUP_USE_VALIDDATE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((1)) FOR [RICH_SETUP_USE_VALIDTIME]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((100)) FOR [RICH_SETUP_LINEFEED]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  CONSTRAINT [DF_BM_RICH_LABELSIZE_FORM_RICH_SETUP_USE_SCALE]  DEFAULT ((0)) FOR [RICH_SETUP_USE_SCALE]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  CONSTRAINT [DF_BM_RICH_LABELSIZE_FORM_RICH_SETUP_USE_SHORT_YEAR]  DEFAULT ((0)) FOR [RICH_SETUP_USE_SHORT_YEAR]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_LABELSIZE_ORDER]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM] ADD  DEFAULT ((0)) FOR [RICH_LOCK_EDIT]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_LABELSIZE_FORM]  WITH CHECK ADD FOREIGN KEY([RICH_BRAND_ID])
REFERENCES [its_labelmanager].[BM_RICH_BRAND] ([RICH_BRAND_ID])
ON DELETE CASCADE
GO
