USE [labelmanager_combine2]
GO

/****** Object:  Table [its_labelmanager].[BM_RICH_BRAND]    Script Date: 2026-07-02 오후 4:13:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [its_labelmanager].[BM_RICH_BRAND](
	[RICH_BRAND_ID] [int] IDENTITY(1,1) NOT NULL,
	[RICH_CUSTOMER_ID] [int] NOT NULL,
	[RICH_BRAND_NAME] [varchar](50) NOT NULL,
	[RICH_BRAND_ORDER] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RICH_BRAND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_BRAND] ADD  DEFAULT ((0)) FOR [RICH_BRAND_ORDER]
GO

ALTER TABLE [its_labelmanager].[BM_RICH_BRAND]  WITH CHECK ADD FOREIGN KEY([RICH_CUSTOMER_ID])
REFERENCES [its_labelmanager].[BM_CUSTOMER] ([RICH_CUSTOMER_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO


