USE [labelmanager_combine2]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [its_labelmanager].[flutter_get_update_notices]
  @userId NVARCHAR(30)
AS
BEGIN
  SET NOCOUNT ON;
  SELECT
    CONVERT(NVARCHAR(4000), UN_MSG COLLATE Korean_100_CI_AS) AS UN_MSG
  FROM BM_UPDATE_NOTICE
  WHERE CONVERT(NVARCHAR(30), UN_USER_ID COLLATE Korean_100_CI_AS) = @userId
END
GO
